EntryApp/config/routes.rb
EntryApp::Application.routes.draw do

  root  'static_pages#home'
  match '/', to: 'static_pages#home', via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'get'
  match '/attempts', to: 'attempts#new', via: 'get'
  match '/controlPanel', to: 'users#controlPanel', via: 'get'

  resources :attempt_answers

  resources :attempt_questions

  resources :answers

  resources :labels_questions

  resources :questions

  resources :labels

  resources :tests

  resources :timetables

  resources :attempts

  resources :roles

  resources :users

  resources :sessions, only: [:new, :create, :destroy]

end

EntryApp/app/models/answer.rb
class Answer < ActiveRecord::Base
	belongs_to :question
	has_many :attempt_answers
end

EntryApp/app/models/attempt.rb
class Attempt < ActiveRecord::Base
	belongs_to :user
	belongs_to :timetable
	has_many :attempt_questions
	has_many :attempt_answers
end

EntryApp/app/models/attempt_answer.rb
class AttemptAnswer < ActiveRecord::Base
	belongs_to :answer
	belongs_to :attempt
end

EntryApp/app/models/attempt_question.rb
class AttemptQuestion < ActiveRecord::Base
	belongs_to :question
	belongs_to :attempt
end

EntryApp/app/models/label.rb
class Label < ActiveRecord::Base
	has_many :labels_questions
end

EntryApp/app/models/labels_question.rb
class LabelsQuestion < ActiveRecord::Base
	belongs_to :label
	belongs_to :question
end

EntryApp/app/models/question.rb
class Question < ActiveRecord::Base
	has_many :labels_questions
	has_many :answers
	has_many :attempt_questions
end

EntryApp/app/models/role.rb
class Role < ActiveRecord::Base
	has_many :users
end

EntryApp/app/models/test.rb
class Test < ActiveRecord::Base
	has_many :timetables
end

EntryApp/app/models/timetable.rb
class Timetable < ActiveRecord::Base
	has_many :attempts
	belongs_to :test
end

EntryApp/app/models/user.rb
class User < ActiveRecord::Base
	belongs_to :role
	has_many :attempts

  
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
 validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                   uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }


  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.hash(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  def admin?
    #logger.debug "IMPORTANT INFO COMING NEXT"
    #logger.debug self.role_id
    return self.role.name=="admin"
  end

	private
	
		def create_remember_token
     	self.remember_token = User.hash(User.new_remember_token)
		end
end

EntryApp/app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_filter :limited_access
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(answer_params)

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @answer, notice: 'Answer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @answer }
      else
        format.html { render action: 'new' }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to answers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:content, :points, :status, :correct, :question_id)
    end
end

EntryApp/app/helpers/answers_helper.rb
module AnswersHelper
end

EntryApp/app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Entry Test Web App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

EntryApp/app/helpers/attempts_helper.rb
module AttemptsHelper
end

EntryApp/app/helpers/labels_helper.rb
module LabelsHelper
end

EntryApp/app/helpers/questions_helper.rb
module QuestionsHelper
end

EntryApp/app/helpers/roles_helper.rb
module RolesHelper
end

EntryApp/app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.hash(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token  = User.hash(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.hash(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end
end

EntryApp/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

EntryApp/app/helpers/tests_helper.rb
module TestsHelper
end

EntryApp/app/helpers/timetables_helper.rb
module TimetablesHelper
end

EntryApp/app/helpers/users_helper.rb
module UsersHelper
end

EntryApp/app/views/answers/_form.html.erb
<%= form_for(@answer) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :points %><br>
    <%= f.number_field :points %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :correct %><br>
    <%= f.check_box :correct %>
  </div>
  <div class="field">
    <%= f.label :question_id %><br>
    <%= f.number_field :question_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

EntryApp/app/views/answers/edit.html.erb
<h1>Editing answer</h1>

<%= render 'form' %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

EntryApp/app/views/answers/index.html.erb
<h1>Listing answers</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Points</th>
      <th>Status</th>
      <th>Correct</th>
      <th>Question</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= answer.content %></td>
        <td><%= answer.points %></td>
        <td><%= answer.status %></td>
        <td><%= answer.correct %></td>
        <td><%= answer.question_id %></td>
        <td><%= link_to 'Show', answer %></td>
        <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
        <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer', new_answer_path %>

EntryApp/app/views/answers/new.html.erb
<h1>New answer</h1>

<%= render 'form' %>

<%= link_to 'Back', answers_path %>

EntryApp/app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @answer.content %>
</p>

<p>
  <strong>Points:</strong>
  <%= @answer.points %>
</p>

<p>
  <strong>Status:</strong>
  <%= @answer.status %>
</p>

<p>
  <strong>Correct:</strong>
  <%= @answer.correct %>
</p>

<p>
  <strong>Question:</strong>
  <%= @answer.question_id %>
</p>

<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>