EntryApp/config/routes.rb
EntryApp::Application.routes.draw do

  root  'static_pages#home'
  match '/', to: 'static_pages#home', via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'get'
  match '/attempts', to: 'attempts#new', via: 'get'
  match '/controlPanel', to: 'users#controlPanel', via: 'get'

  resources :attempt_answers

  resources :attempt_questions

  resources :answers

  resources :labels_questions

  resources :questions

  resources :labels

  resources :tests

  resources :timetables

  resources :attempts

  resources :roles

  resources :users

  resources :sessions, only: [:new, :create, :destroy]

end

EntryApp/app/models/answer.rb
class Answer < ActiveRecord::Base
	belongs_to :question
	has_many :attempt_answers
end

EntryApp/app/models/attempt.rb
class Attempt < ActiveRecord::Base
	belongs_to :user
	belongs_to :timetable
	has_many :attempt_questions
	has_many :attempt_answers
end

EntryApp/app/models/attempt_answer.rb
class AttemptAnswer < ActiveRecord::Base
	belongs_to :answer
	belongs_to :attempt
end

EntryApp/app/models/attempt_question.rb
class AttemptQuestion < ActiveRecord::Base
	belongs_to :question
	belongs_to :attempt
end

EntryApp/app/models/label.rb
class Label < ActiveRecord::Base
	has_many :labels_questions
end

EntryApp/app/models/labels_question.rb
class LabelsQuestion < ActiveRecord::Base
	belongs_to :label
	belongs_to :question
end

EntryApp/app/models/question.rb
class Question < ActiveRecord::Base
	has_many :labels_questions
	has_many :answers
	has_many :attempt_questions
end

EntryApp/app/models/role.rb
class Role < ActiveRecord::Base
	has_many :users
end

EntryApp/app/models/test.rb
class Test < ActiveRecord::Base
	has_many :timetables
end

EntryApp/app/models/timetable.rb
class Timetable < ActiveRecord::Base
	has_many :attempts
	belongs_to :test
end

EntryApp/app/models/user.rb
class User < ActiveRecord::Base
	belongs_to :role
	has_many :attempts

  
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
 validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                   uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }


  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.hash(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  def admin?
    #logger.debug "IMPORTANT INFO COMING NEXT"
    #logger.debug self.role_id
    return self.role.name=="admin"
  end

	private
	
		def create_remember_token
     	self.remember_token = User.hash(User.new_remember_token)
		end
end

EntryApp/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_filter :limited_access
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        manage_answers # insert or update
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render action: 'show', status: :created, location: @question }
      else
        format.html { render action: 'new' }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
   # logger.debug "IMPORTANT INFO COMING NEXT "
   # logger.debug params[:answer]
    respond_to do |format|
      if @question.update(question_params)
        manage_answers # insert or update
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

def manage_answers
    logger.debug "IMPORTANT INFO HERE!"
    logger.debug params[:answer]
    params[:answer].each do |ans|
      ans= ans.merge(:question_id=> @question.id)
      if ans[:id] then
        #update
        Answer.update(ans[:id], ans.permit(:content, :points, :status, :correct, :question_id))
      else
        #create
        Answer.create(ans.permit(:content, :points, :status, :correct, :question_id))
      end
    end
end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:difficulty, :content, :status)
    end
end

EntryApp/app/helpers/answers_helper.rb
module AnswersHelper
end

EntryApp/app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Entry Test Web App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

EntryApp/app/helpers/attempts_helper.rb
module AttemptsHelper
end

EntryApp/app/helpers/labels_helper.rb
module LabelsHelper
end

EntryApp/app/helpers/questions_helper.rb
module QuestionsHelper
end

EntryApp/app/helpers/roles_helper.rb
module RolesHelper
end

EntryApp/app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.hash(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token  = User.hash(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.hash(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end
end

EntryApp/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

EntryApp/app/helpers/tests_helper.rb
module TestsHelper
end

EntryApp/app/helpers/timetables_helper.rb
module TimetablesHelper
end

EntryApp/app/helpers/users_helper.rb
module UsersHelper
end

EntryApp/app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <p> Here you can suggest your question. </p> 
 <%= f.label :content %><br>
 <%= f.text_field :content %> 

 <div class="field">
 <%= f.label :difficulty %>
 
 <%= f.select(:difficulty, options_for_select(["easy","medium","hard"])) %> 
</div> 


 <div class="field"> 
  <%= f.label :label %>
  <%= select_tag(:labels ,options_from_collection_for_select(Label.all, :id, :name) )%> 


</div>



<fieldset id="answers">
    <legend>answers</legend>
    <button onclick="addInput()"  type="button">Add answer</button><br/>
    <%#  AT THE MOMENT THERE IS ONLY ONE TIMESLOT  %>
    <% if @answers=@question.answers and !@question.answers.empty? then 
          @answers.each do |answer|
      %>
      <!-- EDIT EXISTING TIMETABLE-->
              <%= hidden_field_tag 'answer[][id]' ,answer.id  %>
              <%# text_field(:answer, :content, :placeholder => "enter the answer", :value=>answer.content ) %>
              <%= text_field_tag 'answer[][content]' , answer.content %>
              <%= check_box_tag 'answer[][correct]', true, answer.correct %>
          <% end %>
    <%else%>
    <!-- CREATE NEW TIMETABLE -->
       <%= text_field_tag 'answer[][content]'%>
       <%= check_box_tag 'answer[][correct]', true %>
    <% end %>
      

  </fieldset>

  <div class="actions">
    <%= f.submit %>
  </div> 


<% end %>


<script>
answers=$("#answers");
  inputs='<input type="text" name="answer[][content]" value="added with jquery"/> <input type="number" name="answer[][points]" /> <input type="checkbox" name="answer[][correct]" />';
function addInput(){
  answers.append(inputs);
}
</script>

EntryApp/app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

EntryApp/app/views/questions/index.html.erb
<h1>Listing questions</h1>

<table>
  <thead>
    <tr>
      <th>Label</th>
      <th>Difficulty</th>
      <th>Content</th>
      <th>Status</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
      <!--     <td><% question.labels_questions.each do |labelq| %>
      <span><%= labelq.label.name %></span> 
      <% end %></td> -->

         <td><%= question.content %></td>
        <td><%= question.content %></td>
        <td><%= question.difficulty %></td>
        
        <td><%= question.status %></td>

        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

EntryApp/app/views/questions/new.html.erb
<h1>New question</h1>

<p> <strong>Sugest new question:</strong> 

	<br> </p>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

EntryApp/app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p> <strong>Sugested question:</strong> 
	<%= @question.content %> </p>

<p> <strong>The difficulty of your question:</strong> 
	<%= @question.difficulty %> </p>

	<!-- <p> <strong>Label of your Question:</strong> 
		<% @question.labels_questions.each  do |labelq| %>
			<%= labelq.labels_questions.id  %>
			<% end %> 
			</p> -->

<p> <strong>Status:</strong> <%= @question.status %> </p>



<!-- <p>
  <strong>Difficulty:</strong>
  <%= @question.difficulty %>
</p>

<p>
  <strong>Content:</strong>
  <%= @question.content %>
</p>

<p>
  <strong>Status:</strong>
  <%= @question.status %>
</p> -->

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>