EntryApp/config/routes.rb
EntryApp::Application.routes.draw do

  root  'static_pages#home'
  match '/', to: 'static_pages#home', via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'get'
  match '/attempts', to: 'attempts#new', via: 'get'
  match '/controlPanel', to: 'users#controlPanel', via: 'get'

  resources :attempt_answers

  resources :attempt_questions

  resources :answers

  resources :labels_questions

  resources :questions

  resources :labels

  resources :tests

  resources :timetables

  resources :attempts

  resources :roles

  resources :users

  resources :sessions, only: [:new, :create, :destroy]

end

EntryApp/app/models/answer.rb
class Answer < ActiveRecord::Base
	belongs_to :question
	has_many :attempt_answers
end

EntryApp/app/models/attempt.rb
class Attempt < ActiveRecord::Base
	belongs_to :user
	belongs_to :timetable
	has_many :attempt_questions
	has_many :attempt_answers
end

EntryApp/app/models/attempt_answer.rb
class AttemptAnswer < ActiveRecord::Base
	belongs_to :answer
	belongs_to :attempt
end

EntryApp/app/models/attempt_question.rb
class AttemptQuestion < ActiveRecord::Base
	belongs_to :question
	belongs_to :attempt
end

EntryApp/app/models/label.rb
class Label < ActiveRecord::Base
	has_many :labels_questions
end

EntryApp/app/models/labels_question.rb
class LabelsQuestion < ActiveRecord::Base
	belongs_to :label
	belongs_to :question
end

EntryApp/app/models/question.rb
class Question < ActiveRecord::Base
	has_many :labels_questions
	has_many :answers
	has_many :attempt_questions
end

EntryApp/app/models/role.rb
class Role < ActiveRecord::Base
	has_many :users
end

EntryApp/app/models/test.rb
class Test < ActiveRecord::Base
	has_many :timetables
end

EntryApp/app/models/timetable.rb
class Timetable < ActiveRecord::Base
	has_many :attempts
	belongs_to :test
end

EntryApp/app/models/user.rb
class User < ActiveRecord::Base
	belongs_to :role
	has_many :attempts

  
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
 validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                   uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }


  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.hash(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  def admin?
    #logger.debug "IMPORTANT INFO COMING NEXT"
    #logger.debug self.role_id
    return self.role.name=="admin"
  end

	private
	
		def create_remember_token
     	self.remember_token = User.hash(User.new_remember_token)
		end
end

EntryApp/app/helpers/answers_helper.rb
module AnswersHelper
end

EntryApp/app/helpers/attempts_helper.rb
module AttemptsHelper
end

EntryApp/app/helpers/labels_helper.rb
module LabelsHelper
end

EntryApp/app/helpers/questions_helper.rb
module QuestionsHelper
end

EntryApp/app/helpers/roles_helper.rb
module RolesHelper
end

EntryApp/app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.hash(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token  = User.hash(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.hash(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end
end

EntryApp/app/helpers/tests_helper.rb
module TestsHelper
end

EntryApp/app/helpers/timetables_helper.rb
module TimetablesHelper
end

EntryApp/app/helpers/users_helper.rb
module UsersHelper
end

EntryApp/app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="#">Documentation</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",  about_path %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

EntryApp/app/views/layouts/_header.html.erb
	<header class="navbar navbar-fixed-top navbar-inverse">
		<div class="navbar-inner">
			<div class="container">
				<%= link_to "ETWA", root_path, id: "logo" %>
				<nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", '#' %></li>       
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", '#' %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>     
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
			</div>
		</div>
	</header>

EntryApp/app/views/layouts/_shim.html.erb
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

EntryApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= full_title(yield(:title)) %></title>
	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	<%# javascript_include_tag "application", "data-turbolinks-track" => true %>
	<link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css">
<link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.min.css">
<script type="text/javascript" src="http://code.jquery.com/jquery.min.js"></script>
<script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
	<%= csrf_meta_tags %>
	<%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		 <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
		<%= yield %>
		<%= render 'layouts/footer' %>
	</div>
</body>
</html>