EntryApp/config/routes.rb
EntryApp::Application.routes.draw do

  root  'static_pages#home'
  match '/', to: 'static_pages#home', via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'get'
  match '/attempts', to: 'attempts#new', via: 'get'
  match '/controlPanel', to: 'users#controlPanel', via: 'get'

  resources :attempt_answers

  resources :attempt_questions

  resources :answers

  resources :labels_questions

  resources :questions

  resources :labels

  resources :tests

  resources :timetables

  resources :attempts

  resources :roles

  resources :users

  resources :sessions, only: [:new, :create, :destroy]

end

EntryApp/app/models/answer.rb
class Answer < ActiveRecord::Base
	belongs_to :question
	has_many :attempt_answers
end

EntryApp/app/models/attempt.rb
class Attempt < ActiveRecord::Base
	belongs_to :user
	belongs_to :timetable
	has_many :attempt_questions
	has_many :attempt_answers
end

EntryApp/app/models/attempt_answer.rb
class AttemptAnswer < ActiveRecord::Base
	belongs_to :answer
	belongs_to :attempt
end

EntryApp/app/models/attempt_question.rb
class AttemptQuestion < ActiveRecord::Base
	belongs_to :question
	belongs_to :attempt
end

EntryApp/app/models/label.rb
class Label < ActiveRecord::Base
	has_many :labels_questions
end

EntryApp/app/models/labels_question.rb
class LabelsQuestion < ActiveRecord::Base
	belongs_to :label
	belongs_to :question
end

EntryApp/app/models/question.rb
class Question < ActiveRecord::Base
	has_many :labels_questions
	has_many :answers
	has_many :attempt_questions
end

EntryApp/app/models/role.rb
class Role < ActiveRecord::Base
	has_many :users
end

EntryApp/app/models/test.rb
class Test < ActiveRecord::Base
	has_many :timetables
end

EntryApp/app/models/timetable.rb
class Timetable < ActiveRecord::Base
	has_many :attempts
	belongs_to :test
end

EntryApp/app/models/user.rb
class User < ActiveRecord::Base
	belongs_to :role
	has_many :attempts

  
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
 validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                   uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }


  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.hash(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  def admin?
    #logger.debug "IMPORTANT INFO COMING NEXT"
    #logger.debug self.role_id
    return self.role.name=="admin"
  end

	private
	
		def create_remember_token
     	self.remember_token = User.hash(User.new_remember_token)
		end
end

EntryApp/app/controllers/attempt_answers_controller.rb
class AttemptAnswersController < ApplicationController
  before_action :set_attempt_answer, only: [:show, :edit, :update, :destroy]

  # GET /attempt_answers
  # GET /attempt_answers.json
  def index
    @attempt_answers = AttemptAnswer.all
  end

  # GET /attempt_answers/1
  # GET /attempt_answers/1.json
  def show
  end

  # GET /attempt_answers/new
  def new
    @attempt_answer = AttemptAnswer.new
  end

  # GET /attempt_answers/1/edit
  def edit
  end

  # POST /attempt_answers
  # POST /attempt_answers.json
  def create
    @attempt_answer = AttemptAnswer.new(attempt_answer_params)

    respond_to do |format|
      if @attempt_answer.save
        format.html { redirect_to @attempt_answer, notice: 'Attempt answer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @attempt_answer }
      else
        format.html { render action: 'new' }
        format.json { render json: @attempt_answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attempt_answers/1
  # PATCH/PUT /attempt_answers/1.json
  def update
    respond_to do |format|
      if @attempt_answer.update(attempt_answer_params)
        format.html { redirect_to @attempt_answer, notice: 'Attempt answer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @attempt_answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attempt_answers/1
  # DELETE /attempt_answers/1.json
  def destroy
    @attempt_answer.destroy
    respond_to do |format|
      format.html { redirect_to attempt_answers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attempt_answer
      @attempt_answer = AttemptAnswer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attempt_answer_params
      params.require(:attempt_answer).permit(:answer_id, :attempt_id, :chosen)
    end
end

EntryApp/app/helpers/answers_helper.rb
module AnswersHelper
end

EntryApp/app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Entry Test Web App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

EntryApp/app/helpers/attempt_answers_helper.rb
module AttemptAnswersHelper
end

EntryApp/app/helpers/attempts_helper.rb
module AttemptsHelper
end

EntryApp/app/helpers/labels_helper.rb
module LabelsHelper
end

EntryApp/app/helpers/questions_helper.rb
module QuestionsHelper
end

EntryApp/app/helpers/roles_helper.rb
module RolesHelper
end

EntryApp/app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.hash(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token  = User.hash(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.hash(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end
end

EntryApp/app/helpers/tests_helper.rb
module TestsHelper
end

EntryApp/app/helpers/timetables_helper.rb
module TimetablesHelper
end

EntryApp/app/helpers/users_helper.rb
module UsersHelper
end

EntryApp/app/views/attempt_answers/_form.html.erb
<%= form_for(@attempt_answer) do |f| %>
  <% if @attempt_answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attempt_answer.errors.count, "error") %> prohibited this attempt_answer from being saved:</h2>

      <ul>
      <% @attempt_answer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :answer_id %><br>
    <%= f.number_field :answer_id %>
  </div>
  <div class="field">
    <%= f.label :attempt_id %><br>
    <%= f.number_field :attempt_id %>
  </div>
  <div class="field">
    <%= f.label :chosen %><br>
    <%= f.check_box :chosen %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

EntryApp/app/views/attempt_answers/edit.html.erb
<h1>Editing attempt_answer</h1>

<%= render 'form' %>

<%= link_to 'Show', @attempt_answer %> |
<%= link_to 'Back', attempt_answers_path %>

EntryApp/app/views/attempt_answers/index.html.erb
<h1>Listing attempt_answers</h1>

<table>
  <thead>
    <tr>
      <th>Answer</th>
      <th>Attempt</th>
      <th>Chosen</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @attempt_answers.each do |attempt_answer| %>
      <tr>
        <td><%= attempt_answer.answer_id %></td>
        <td><%= attempt_answer.attempt_id %></td>
        <td><%= attempt_answer.chosen %></td>
        <td><%= link_to 'Show', attempt_answer %></td>
        <td><%= link_to 'Edit', edit_attempt_answer_path(attempt_answer) %></td>
        <td><%= link_to 'Destroy', attempt_answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attempt answer', new_attempt_answer_path %>

EntryApp/app/views/attempt_answers/new.html.erb
<h1>New attempt_answer</h1>

<%= render 'form' %>

<%= link_to 'Back', attempt_answers_path %>

EntryApp/app/views/attempt_answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Answer:</strong>
  <%= @attempt_answer.answer_id %>
</p>

<p>
  <strong>Attempt:</strong>
  <%= @attempt_answer.attempt_id %>
</p>

<p>
  <strong>Chosen:</strong>
  <%= @attempt_answer.chosen %>
</p>

<%= link_to 'Edit', edit_attempt_answer_path(@attempt_answer) %> |
<%= link_to 'Back', attempt_answers_path %>